build:
    environment:
        php:
            version: 5.5
            version: 5.6
            version: 7.0
    
    dependencies:
        before:
            - 'composer global require "fxp/composer-asset-plugin:^1.2.0"'
    
    project_setup:
        before:
            - mysql -e "CREATE DATABASE yii2advanced_test"
            - php yii_test migrate --interactive=0
        
    tests:
        override:
            - ./vendor/codeception/base/codecept run