build:
    environment:
        php:
            version: 5.5
            version: 5.6
            version: 7.0
    tests:
        override:
            - ./vendor/codeception/base/codecept run