build:
    environment:
        php:
            version: 5.5
            version: 5.6
            version: 7.0
    
    project_setup:
        before:
            - mysql -e "CREATE DATABASE yii2advanced_test"
        
    tests:
        override:
            - ./vendor/codeception/base/codecept run